# Copyright 2023 - 2024 California Department of Motor Vehicles
# Copyright 2023 - 2024 Digital Bazaar, Inc.
#
# SPDX-License-Identifier: BSD-3-Clause

steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args: [
      'build',
      '--build-arg',
      'NODE_AUTH_TOKEN=$(secrets.NODE_AUTH_TOKEN)',
      '-t',
      '$(secrets.TAG_NAME)',
      '.'
    ]

  # Paso 2: Empujar la imagen Docker al repositorio
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image to Repository'
    args: [
      'push',
      '$(gcloud secrets versions access latest --secret=TAG_NAME)'
    ]

  # Paso 3: Atacar la imagen con Binary Authorization
  - name: 'gcr.io/$PROJECT_ID/cloudbuild-attestor'
    id: 'Attest Image (Binary Auth)'
    entrypoint: 'sh'
    args:
      - -xe
      - -c
      - |-
        FQ_DIGEST=$(gcloud container images describe --format 'value(image_summary.fully_qualified_digest)' $(gcloud secrets versions access latest --secret=TAG_NAME))
        /scripts/create_attestation.sh \
          -p "$PROJECT_ID" \
          -i "$${FQ_DIGEST}" \
          -a "$(gcloud secrets versions access latest --secret=VULNZ_ATTESTOR)" \
          -v "$(gcloud secrets versions access latest --secret=VULNZ_KMS_KEY_VERSION)" \
          -k "$(gcloud secrets versions access latest --secret=VULNZ_KMS_KEY)" \
          -l "$(gcloud secrets versions access latest --secret=KMS_LOCATION)" \
          -r "$(gcloud secrets versions access latest --secret=KMS_KEYRING)"
options:
  logging: CLOUD_LOGGING_ONLY
