# Copyright 2023 - 2024 California Department of Motor Vehicles
# Copyright 2023 - 2024 Digital Bazaar, Inc.
#
# SPDX-License-Identifier: BSD-3-Clause

steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args: [
      'build',
      '--build-arg',
      'NODE_AUTH_TOKEN=$(secrets.NODE_AUTH_TOKEN)',
      '-t',
      'gcr.io/tantan-gc/opencred:latest',
      '.'
    ]

  # Paso 2: Empujar la imagen Docker al repositorio
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image to Repository'
    args: [
      'push',
      'gcr.io/tantan-gc/opencred:latest'
    ]

  # Paso 3: Atacar la imagen con Binary Authorization
  - name: 'gcr.io/tantan-gc/cloudbuild-attestor'
    id: 'Attest Image (Binary Auth)'
    entrypoint: 'sh'
    args:
      - -xe
      - -c
      - |-
        FQ_DIGEST=$(gcloud container images describe --format 'value(image_summary.fully_qualified_digest)' gcr.io/tantan-gc/opencred:latest)
        /scripts/create_attestation.sh \
          -p "tatan-gc" \
          -i "$${FQ_DIGEST}" \
          -a "$(secrets.VULNZ_ATTESTOR)" \
          -v "$(secrets.VULNZ_KMS_KEY_VERSION)" \
          -k "$(secrets.VULNZ_KMS_KEY)" \
          -l "$(secrets.KMS_LOCATION)" \
          -r "$(secrets.KMS_KEYRING)"
options:
  logging: CLOUD_LOGGING_ONLY
