# Copyright 2023 - 2024 California Department of Motor Vehicles
# Copyright 2023 - 2024 Digital Bazaar, Inc.
#
# SPDX-License-Identifier: BSD-3-Clause

app:
  #express: 
    #httpOnly: true
  server:
    baseUri: https://opencred-585542331364.us-central1.run.app
    #ports:
      #http: 22080
      #https: 22443
  mongodb:
    url: mongodb://34.230.17.226:27017/opencred
  opencred:
    caStore:
      - pem: |
          -----BEGIN CERTIFICATE-----
          MIICLjCCAdSgAwIBAgIUXrDPrioY9PCUO5hCXJTsVIZwI0cwCgYIKoZIzj0EAwIw
          UDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVTLUNBMQwwCgYDVQQKDANETVYxIzAh
          BgNVBAMMGkNhbGlmb3JuaWEgRE1WIFJvb3QgQ0EgVUFUMB4XDTIzMDQxNDE3MjQ0
          N1oXDTMzMDIyMDE3MjQ0N1owUDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVTLUNB
          MQwwCgYDVQQKDANETVYxIzAhBgNVBAMMGkNhbGlmb3JuaWEgRE1WIFJvb3QgQ0Eg
          VUFUMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEORXa3DGvoGS0s6S71Vw5oKEw
          DdPubWyg75A2p1hca4b66MA0LXUWjoz1cIKUJpyEket9ajEx5+hQvB3yvycKVqOB
          izCBiDAdBgNVHQ4EFgQUSWhCfS8C3wEPseC28ScmFn0j25UwEgYDVR0TAQH/BAgw
          BgEB/wIBADALBgNVHQ8EBAMCAQYwHQYDVR0SBBYwFIESZXhhbXBsZUBkbXYuY2Eu
          Z292MCcGA1UdHwQgMB4wHKAaoBiGFmh0dHBzOi8vZG12LmNhLmdvdi9jcmwwCgYI
          KoZIzj0EAwIDSAAwRQIgbpRE08g3aId6e2QULkmlTqnGq0+6kqLltHfjmO6/5MEC
          IQDJdY3WnkpFhPw+Ej3ANlFzwvaDgfaacODGR0pFvBQwlg==
          -----END CERTIFICATE-----
      - pem: |      
          -----BEGIN CERTIFICATE-----
          MIICPzCCAeWgAwIBAgIUXd0okOOM5cylFwc2WNK7D2O+ArAwCgYIKoZIzj0EAwIw
          UTELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVTLUNBMQ8wDQYDVQQKDAZDQS1ETVYx
          ITAfBgNVBAMMGENhbGlmb3JuaWEgRE1WIElBQ0EgUm9vdDAeFw0yMzAzMDExNzE3
          MzlaFw0zMzAxMDcxNzE3MzlaMFExCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVVUy1D
          QTEPMA0GA1UECgwGQ0EtRE1WMSEwHwYDVQQDDBhDYWxpZm9ybmlhIERNViBJQUNB
          IFJvb3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARgzKB5QsRXYGxmIapA3ilL
          oXCDxgTMI2JArA72VQ9gL2DIKkBAclKYtix7vQwUbhbH76mnmbOFSxYlCJtilfl1
          o4GaMIGXMB0GA1UdDgQWBBS7fXVnknpvz59ye7gK9zcvnAxQNjASBgNVHRMBAf8E
          CDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAfBgNVHRIEGDAWgRRpYWNhLXJvb3RA
          ZG12LmNhLmdvdjAxBgNVHR8EKjAoMCagJKAihiBodHRwczovL2NybC5kbXYuY2Eu
          Z292L2lhY2Evcm9vdDAKBggqhkjOPQQDAgNIADBFAiAJriK4wEUzgDCK++tIIW+g
          XASUIIcG/XhBNxuk2uHd7QIhAKWC8LFaM8qFsvlujtZZf647zD8BBc6kicj1Imw/
          wujS
          -----END CERTIFICATE-----
      - pem: |
          -----BEGIN CERTIFICATE-----
          MIICeDCCAh+gAwIBAgIUNb1vs9nrIFNkxW/Ah5RbqSk5D48wCgYIKoZIzj0EAwIw
          UTELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVTLUNBMQ8wDQYDVQQKDAZDQS1ETVYx
          ITAfBgNVBAMMGENhbGlmb3JuaWEgRE1WIElBQ0EgUm9vdDAeFw0yNDAxMjYyMDM5
          MzlaFw0yNTAxMjUyMDM5MzlaMFYxCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVVUy1D
          QTEPMA0GA1UECgwGQ0EtRE1WMSYwJAYDVQQDDB1DYWxpZm9ybmlhIERNViBJQUNB
          IFZDIFNpZ25lcjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABN7bkMmpNWsUS3MA
          l7PcrUkguJMQuPj2nmYaULrAJSN6o46TYiv/hn03CtkVDhIOL3Lot8tVYWBqNPmZ
          fi96PVKjgc8wgcwwHQYDVR0OBBYEFPjtmX0B60mQQBlRTa+nUMHAHb7EMB8GA1Ud
          IwQYMBaAFLt9dWeSem/Pn3J7uAr3Ny+cDFA2MB0GCWCGSAGG+EIBDQQQFg5DYWxp
          Zm9ybmlhIERNVjAOBgNVHQ8BAf8EBAMCB4AwIQYDVR0SBBowGIEWaWFjYS1zaWdu
          ZXJAZG12LmNhLmdvdjA4BgNVHR8EMTAvMC2gK6AphidodHRwczovL2NybC5kbXYu
          Y2EuZ292L2lhY2EvbWRvYy1zaWduZXIwCgYIKoZIzj0EAwIDRwAwRAIgMsZMt2+6
          92d8o3ndNSyLWGcGhKcNaDVFgzh6NVZez8ICIApUEIiGIflkIAAkuxgepibKAYT8
          +Z4B8u20Qusl/PH/
          -----END CERTIFICATE-----
    signingKeys:
      - type: ES256
        id: 8b12ea18935db1c596162df68f5e2c60ec3d26e0f5aa843da224df609b581471
        privateKeyPem: |
          -----BEGIN PRIVATE KEY-----
          MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQggNKm7C5ntd9S8YlI
          KshMnBjS0EYz8yLDZ5+nWthsYiihRANCAARFqQBgzNAbAO3qJdykU9VZSij1ilx3
          V9rYpnYA1oBP8RRdGJEfch/1DPSI3CUdfysKCEix0vMiR1xHG76fcgHY
          -----END PRIVATE KEY-----
        publicKeyPem: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERakAYMzQGwDt6iXcpFPVWUoo9Ypc
          d1fa2KZ2ANaAT/EUXRiRH3If9Qz0iNwlHX8rCghIsdLzIkdcRxu+n3IB2A==
          -----END PUBLIC KEY-----
        purpose:
          - id_token
          - authorization_request
    relyingParties:
      - name: "Test Relying Party (Native)"
        clientId: "rp1"
        clientSecret: "DeepestAndDarkest"
        description: "Relying Party Test App"
        primaryLogo: "https://placekitten.com/200/200"
        primaryLink: "https://modelo-landing.web.app/main_page.html"
        secondaryLogo: "https://placekitten.com/200/200"
        secondaryLink: "https://modelo-landing.web.app/"
        homeLink: "https://modelo-landing.web.app/main_page.html"
        explainerVideo:
          id: "<YOUTUBE ID>"
          provider: youtube
        backgroundImage: "https://placekitten.com/800/200"
        redirectUri: "https://modelo-landing.web.app/main_page.html"
        idTokenExpirySeconds: 3600
        claims:
          - name: "dl_number"
            path: "driversLicense.document_number"
        brand:
          cta: "#0B669D"
          primary: "#045199"
          header: "#0979c4"
        scopes:
          - name: "openid"
            description: "Open ID Connect"
        workflow:
          type: native
          id: z1A32xJZGqBeAEcMq56avmw2L
          initialStep: default
          steps:
            default:
              createChallenge: true
              verifiablePresentationRequest: >
                {
                  "query": {
                    "type": "QueryByExample",
                    "credentialQuery": {
                      "reason": "Please present your VC.",
                      "example": {
                        "type": [
                          "Iso18013DriversLicenseCredential"
                        ]
                      }
                    }
                  }
                }
              constraintsOverride: >
                {
                  "fields": [
                    {
                      "path": [
                        "$.vc.type"
                      ],
                      "filter": {
                        "type": "string",
                        "pattern": "Iso18013DriversLicenseCredential"
                      }
                    }
                  ]
                }
    options:
      exchangeProtocols:
        - chapi
        - openid4vp
    defaultBrand:
      cta: "#0B669D"
      primary: "#045199"
      header: "#0979c4"
    defaultLanguage: es
    translations:
      en:
        translations:
          en: English
          es: Spanish
        translate: Translate
        qrTitle: Login with your Wallet app
        qrPageExplain: Scan the following QR Code using the Wallet app on your phone.
        qrPageExplainHelp: (<a href="https://youtube.com">How do I do it?</a>)
        qrFooter: "Note: Already on your phone with the Wallet app? Open the Wallet app, then come back and tap on the QR code above."
        qrFooterHelp: Difficulty using the Wallet app to login? revert to using password <a href="#">here</a>
        qrDisclaimer: If you don't have a Wallet app download it from the app store.
        qrExplainerText: (How do I do it?)
        openid4vpAnotherWay: "Scan a QR code"
        chapiPageAnotherWay: "Looking for a QR code to scan with your wallet app instead?"
        loginCta: "Login with your credential wallet"
        loginExplain: "To login with your credential wallet, you will need to have the credential wallet app <with configurable URL to app stores> installed"
        appInstallExplain: "If you don't have a credential wallet yet, you can get one by downloading the credential wallet app <with configurable URL to app stores>"
        appCta: "Open wallet app"
        copyright: "Powered by OpenCred"
        pageTitle: "Login"
        home: "Home"
        verificationSuccess: "Success! Your credential has been shared."
        exchangeActiveGoBack: Back
        exchangeActiveExpiryMessage: "Please complete within the allotted time:"
        exchangeErrorTitle: Exchange failed
        exchangeErrorSubtitle: "Error details:"
        exchangeResetTitle: Please try again.
        exchangeReset: Retry exchange
      es:
        translations:
          en: Inglés
          es: Español
        translate: Traducción
        qrTitle: Iniciar sesión con tu aplicación de Wallet Tan Tan
        qrPageExplain: Escanea el siguiente código QR usando la aplicación de Wallet en tu teléfono.
        qrPageExplainHelp: (<a href="https://youtube.com">¿Cómo lo hago?</a>)
        qrFooter: "Nota: ¿Ya tienes la aplicación de Wallet en tu teléfono? Abre la aplicación de Wallet, luego regresa y toca el código QR de arriba."
        qrFooterHelp: ¿Dificultades para usar la aplicación de Wallet para iniciar sesión? Vuelve a usar la contraseña <a href="#">aquí</a>.
        qrDisclaimer: Si no tienes una aplicación de Wallet, descárgala desde la tienda de aplicaciones.
        qrExplainerText: (¿Cómo lo hago?)
        openid4vpAnotherWay: "Escanea un código QR"
        chapiPageAnotherWay: "¿Buscas un código QR para escanear con tu aplicación de Wallet?"
        loginCta: "Iniciar sesión con tu billetera de credenciales"
        loginExplain: "Para iniciar sesión con tu billetera de credenciales, necesitarás tener instalada la aplicación de billetera de credenciales <con URL configurable a las tiendas de aplicaciones>"
        appInstallExplain: "Si aún no tienes una billetera de credenciales, puedes obtener una descargando la aplicación de billetera de credenciales <con URL configurable a las tiendas de aplicaciones>"
        appCta: "Abrir aplicación de Wallet"
        copyright: "Con la tecnología de OpenCred"
        pageTitle: "Iniciar sesión"
        home: "Inicio"
        verificationSuccess: ¡Éxito!
    didWeb:
      mainEnabled: true
